# (!) elasticsearch requires vm.max_map_count=262144 set in /etc/sysctl.conf
# you can check to see if the ports were opened using lsof -i -P | grep LISTEN

version: '3.5'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  elasticsearch_data:
    driver: local

